apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack-nats.yml --volumes hostPath
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: nats
  name: nats
  namespace: common-infrastructure
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nats
    spec:
      containers:
      - image: nats
        name: nats
        ports:
        - containerPort: 8222
        - containerPort: 4222
        resources: {}
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: broker
status: {}
