version: '3'
services:
  nats:
    image: 'nats'
    ports:
      - "8222:8222"
      - "4222:4222"
  publisher:
    image: publisher:latest
    depends_on:
      - nats
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: 'nats'
      broker_port_key: "4222"
      messages_per_second_key: "1000"
      test_duration_in_sec_key: "100"
      type_of_messaging_queue_key: 'NATS'
  subscriber:
    image: subscriber:latest
    depends_on:
      - nats
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: "nats"
      broker_port_key: "4222"
      type_of_messaging_queue_key: 'NATS'
  transformer:
    image: transformer:latest
    depends_on:
      - nats
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: "nats"
      broker_port_key: "4222"
      type_of_messaging_queue_key: 'NATS'
  orchestrator:
    image: orchestrator:latest
    environment:
      distribute_ports: 'false'
      is_loopback_key: 'false'
