version: '3.3'
services:
  artemis:
    image: vromero/activemq-artemis
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5445:5445"
      - "5672:5672"
      - "1889:1883"
      - "61613:61613"
    deploy:
      replicas: 1
      #update_config:
      #  parallelism: 2
      #  delay: 10s
      restart_policy:
        condition: on-failure
    environment:
       ARTEMIS_USERNAME: "guest"
       ARTEMIS_PASSWORD: "guest"
    #volumes:
    #   - "./infrastructure_components/publisher_subscriber/activemq_artemis/data:/var/lib/artemis/data"
    #   - "./infrastructure_components/publisher_subscriber/activemq_artemis/etc:/var/lib/artemis/etc"
  publisher:
    image: publisher:latest
    depends_on:
      - redis-commander
      - artemis
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: 'artemis'
      broker_port_key: "1883"
      publisher_topic_key: "ThingspaceSDK/12344444444444555/UNITOnBoard-publisher"
      message_key: "{\
                     \"lastUpdated\": \"2018-11-19T18:21:03Z\",\
                     \"unitName\": \"VZW_LH_UNIT_01\",\
                     \"unitMacId\": \"864508030027459\",\
                     \"sensor\": {\
                       \"name\": \"cHe_AssetTracker\",\
                       \"characteristics\": [\
                         {\
                           \"characteristicsName\": \"temperature\",\
                           \"currentValue\": \"30.2999\",\
                           \"readLevel\": \"R\",\
                           \"parameterType\": \"Number\",\
                           \"measurementUnit\": \"Celcius\"\
                         }\
                       ]\
                     }\
                   }"
      messages_per_second_key: "100"
      test_duration_in_sec_key: "100"
      log_level_key: "info"
      redis_server_hostname_key: 'redis'
      redis_server_port_key:  '6379'
      redis_log_keyname_key: 'produce_load_test_events'
      total_job_enqueued_count_redis_name_key: 'total_produced_count'
      total_job_dequeued_count_redis_name_key: 'total_consumed_count'
      type_of_messaging_queue_key: 'RabbitMQ'
  subscriber:
    image: subscriber:latest
    depends_on:
      - redis-commander
      - artemis
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: "artemis"
      broker_port_key: "1883"
      subscriber_topic_key: "ThingspaceSDK/12344444444444555/UNITOnBoard-subscriber"
      average_latency_for_n_sec_key: "1"
      test_duration_in_sec_key: "100"
      log_level_key: "info"
      max_consumer_threads_key: "1"
      redis_server_hostname_key: 'redis'
      redis_server_port_key:  '6379'
      redis_log_keyname_key: 'consume_load_test_events'
      latency_publish_key: 'latency_results'
      total_job_enqueued_count_redis_name_key: 'total_produced_count'
      total_job_dequeued_count_redis_name_key: 'total_consumed_count'
      latency_compute_start_key_name_key: 'start_time'
      type_of_messaging_queue_key: 'RabbitMQ'
  transformer:
    image: transformer:latest
    depends_on:
      - redis-commander
      - artemis
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: "artemis"
      broker_port_key: "1883"
      subscriber_topic_key: "ThingspaceSDK/12344444444444555/UNITOnBoard-publisher"
      publisher_topic_key: "ThingspaceSDK/12344444444444555/UNITOnBoard-subscriber"
      test_duration_in_sec_key: "100"
      log_level_key: "info"
      redis_server_hostname_key: 'redis'
      redis_server_port_key:  '6379'
      redis_log_keyname_key: 'transformer_load_test_events'
      total_job_enqueued_count_redis_name_key: 'total_produced_count'
      total_job_dequeued_count_redis_name_key: 'total_consumed_count'
      type_of_messaging_queue_key: 'RabbitMQ'
  plotter:
    image: plotter:latest
    depends_on:
      - redis-commander
    ports:
      - "8889:8888"
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      redis_server_hostname_key: 'redis'
      redis_server_port_key:  '6379'
      redis_log_keyname_key: 'plotter_load_test_events'
      latency_redis_key: 'latency_results'
      latency_compute_start_key_name_key: 'start_time'
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis:redis:6379
    ports:
      - 8082:8081
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./infrastructure_components/portainer/data:/data

#  logspout:
#    image: gliderlabs/logspout:latest
#    command: 'syslog://:5000'
#    depends_on:
#      - logstash
#    volumes:
#      - '/var/run/docker.sock:/var/run/docker.sock'

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.4
    user: root
    depends_on:
      - elasticsearch
      - logstash
      - kibana
    volumes:
      - ./plotter/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
      - strict.perms=false
  logstash:
    build:
      context: ./plotter/logstash
      dockerfile: Dockerfile
    image: logstash:latest
    ports:
      - "5044:5044"
      - "9600:9600"
    depends_on:
      - elasticsearch
      - kibana
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.7.1
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml

configs:
  elastic_config:
    file: ./plotter/elasticsearch/config/elasticsearch.yml
  logstash_config:
    file: ./plotter/logstash/config/logstash.yml
  logstash_pipeline:
    file: ./plotter/logstash/pipeline/logstash.conf
  kibana_config:
    file: ./plotter/kibana/config/kibana.yml
  filebeat_config:
    file: ./plotter/filebeat/filebeat.docker.yml
