version: '3'
services:
    redis:
      image: redis:latest
      ports:
        - "6379:6379"
    redis-commander:
      image: rediscommander/redis-commander:latest
      environment:
        - REDIS_HOSTS=redis:redis:6379
      ports:
        - 8082:8081
    orchestrator:
      image: orchestrator:latest
      depends_on:
        - redis-commander
      deploy:
        replicas: 1
        #      resources:
        #        limits:
        #          cpus: "0.8"
        #          memory: 2000M
        restart_policy:
          condition: none
      environment:
        redis_server_hostname_key: 'redis'
        redis_server_port_key:  '6379'
        redis_log_keyname_key: 'orchestrator_load_test_events'
        # distribute_ports: 'true'
        # is_loopback_key: 'true'
        publisher_key_name: "publisher"
        publisher_hash_table_name: "publisher_hash_table"
        subscriber_key_name: "subscriber"
        subscriber_hash_table_name: "subscriber_hash_table"
        transformer_key_name: "transformer"
        transformer_hash_table_name: "transformer_hash_table"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    filebeat:
      image: docker.elastic.co/beats/filebeat:6.5.4
      #image: docker.elastic.co/beats/filebeat:6.7.1
      user: root
      volumes:
        - ./plotter/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
      environment:
        #- output.logstash.hosts=["logstash:5044"]
        - strict.perms=false
        #plotter:
    #  image: plotter:latest
    #  depends_on:
    #    - redis-commander
    #  deploy:
    #    replicas: 1
        #      resources:
        #        limits:
        #          cpus: "0.8"
        #          memory: 2000M
    #    restart_policy:
    #      condition: none
    #  environment:
    #    html_filename_key: '/opt/html_graph_storage/latency.html'
    #    redis_server_hostname_key: 'redis'
    #    redis_server_port_key:  '6379'
    #    redis_log_keyname_key: 'plotter_load_test_events'
    #    latency_redis_key: 'latency_results'
    #    latency_compute_start_key_name_key: 'start_time'
    #  volumes:
    #    - ./html_graph_storage:/opt/html_graph_storage
    #    - /var/run/docker.sock:/var/run/docker.sock
    #    - "/etc/timezone:/etc/timezone:ro"
    #    - "/etc/localtime:/etc/localtime:ro"
    #displayer:
    #  image: displayer:latest
    #  ports:
    #    - "8888:8888"
    #  deploy:
    #    replicas: 1
        #      resources:
        #        limits:
        #          cpus: "0.8"
        #          memory: 2000M
    #    restart_policy:
    #      condition: none
    #  environment:
    #    html_filename_key: '/opt/html_graph_storage/latency.html'
    #  volumes:
    #    - ./html_graph_storage:/opt/html_graph_storage:ro
    #    - /var/run/docker.sock:/var/run/docker.sock
    #    - "/etc/timezone:/etc/timezone:ro"
    #    - "/etc/localtime:/etc/localtime:ro"
    #cadvisor:
    #  image: google/cadvisor:latest
    #  ports:
    #    - 8089:8080
    #  volumes:
    #    - /:/rootfs:ro
    #    - /var/run:/var/run:rw
    #    - /sys:/sys:ro
    #    - /var/lib/docker/:/var/lib/docker:ro
    #netdata:
    #  image: netdata/netdata
    #  ports:
    #    - 19999:19999
    #  volumes:
    #    - /proc:/host/proc:ro
    #    - /sys:/host/sys:ro
    #    - /var/run/docker.sock:/var/run/docker.sock:ro
    #  cap_add:
    #    - SYS_PTRACE
    #  security_opt:
    #    - apparmor:unconfined