version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8-rc-management
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "1889:1883"
    volumes:
      - "./infrastructure_components/publisher_subscriber/rabbit_msgq_api/rabbitmq_conf_plugins/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./infrastructure_components/publisher_subscriber/rabbit_msgq_api/rabbitmq_conf_plugins/rabbitmq-env.conf:/etc/rabbitmq/rabbitmq-env.conf"
      - "./infrastructure_components/publisher_subscriber/rabbit_msgq_api/rabbitmq_conf_plugins/rabbitmq-modified.conf:/etc/rabbitmq/rabbitmq-modified.conf"
      - "./infrastructure_components/publisher_subscriber/rabbit_msgq_api/rabbitmq_conf_plugins/rabbitmq-definitions.json:/etc/rabbitmq/rabbitmq-definitions.json"
  publisher:
    image: publisher:latest
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: '192.168.106.45'
      broker_port_key: "30080"
      messages_per_second_key: "500"
      test_duration_in_sec_key: "100"
      type_of_messaging_queue_key: 'RabbitMQ'
  subscriber:
    image: subscriber:latest
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: "192.168.106.45"
      broker_port_key: "30080"
      type_of_messaging_queue_key: 'RabbitMQ'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  transformer:
    image: transformer:latest
    depends_on:
      - rabbitmq
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: "192.168.106.45"
      broker_port_key: "30080"
      type_of_messaging_queue_key: 'RabbitMQ'
  orchestrator:
    image: orchestrator:latest
    environment:
      distribute_ports: 'false'
      is_loopback_key: 'false'
