version: '3.7'
services:
  emq:
    image: emqx/emqx:latest
    ports:
        - "18083:18083"
        - "1883:1883"
        - "4369:4369"
    environment:
        EMQX_LOADED_PLUGINS: "emqx_auth_redis,emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
        EMQX_AUTH__REDIS__SERVER: "redis:6379"
    sysctls:
        - fs.file-max=2097152
        - fs.nr_open=2097152
        - net.core.somaxconn=32768
        - net.ipv4.tcp_max_syn_backlog=16384
        - net.core.netdev_max_backlog=16384
        - net.ipv4.ip_local_port_range=1000 65535
        - net.core.rmem_default=262144
        - net.core.wmem_default=262144
        - net.core.rmem_max=16777216
        - net.core.wmem_max=16777216
        - net.core.optmem_max=16777216
        - net.ipv4.tcp_rmem=1024 4096 16777216
        - net.ipv4.tcp_wmem=1024 4096 16777216
        - net.ipv4.tcp_max_tw_buckets=1048576
        - net.ipv4.tcp_fin_timeout=15
  publisher:
    image: publisher:latest
    depends_on:
      - redis-commander
      - emq
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: 'emq'
      broker_port_key: "1883"
      publisher_key_name: "publisher"
      hash_table_name: "publisher_hash_table"
      message_key: "{\
                     \"lastUpdated\": \"2018-11-19T18:21:03Z\",\
                     \"unitName\": \"VZW_LH_UNIT_01\",\
                     \"unitMacId\": \"864508030027459\",\
                     \"sensor\": {\
                       \"name\": \"cHe_AssetTracker\",\
                       \"characteristics\": [\
                         {\
                           \"characteristicsName\": \"temperature\",\
                           \"currentValue\": \"30.2999\",\
                           \"readLevel\": \"R\",\
                           \"parameterType\": \"Number\",\
                           \"measurementUnit\": \"Celcius\"\
                         }\
                       ]\
                     }\
                   }"
      messages_per_second_key: "1000"
      test_duration_in_sec_key: "100"
      log_level_key: "info"
      redis_server_hostname_key: 'redis'
      redis_server_port_key:  '6379'
      redis_log_keyname_key: 'produce_load_test_events'
      total_job_enqueued_count_redis_name_key: 'total_produced_count'
      total_job_dequeued_count_redis_name_key: 'total_consumed_count'
      type_of_messaging_queue_key: 'RabbitMQ'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  subscriber:
    image: subscriber:latest
    depends_on:
      - redis-commander
      - emq
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: "emq"
      broker_port_key: "1883"
      subscriber_key_name: "subscriber"
      hash_table_name: "subscriber_hash_table"
      average_latency_for_n_sec_key: "1"
      log_level_key: "info"
      max_consumer_threads_key: "1"
      redis_server_hostname_key: 'redis'
      redis_server_port_key:  '6379'
      redis_log_keyname_key: 'consume_load_test_events'
      latency_publish_key: 'latency_results'
      total_job_enqueued_count_redis_name_key: 'total_produced_count'
      total_job_dequeued_count_redis_name_key: 'total_consumed_count'
      latency_compute_start_key_name_key: 'start_time'
      type_of_messaging_queue_key: 'RabbitMQ'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
  transformer:
    image: transformer:latest
    depends_on:
      - redis-commander
      - emq
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: "emq"
      broker_port_key: "1883"
      transformer_key_name: "transformer"
      hash_table_name: "transformer_hash_table"
      log_level_key: "info"
      redis_server_hostname_key: 'redis'
      redis_server_port_key:  '6379'
      redis_log_keyname_key: 'transformer_load_test_events'
      total_job_enqueued_count_redis_name_key: 'total_produced_count'
      total_job_dequeued_count_redis_name_key: 'total_consumed_count'
      type_of_messaging_queue_key: 'RabbitMQ'
