apiVersion: v1
kind: Service
metadata:
  name: emqx
spec:
  ports:
  - name: "32333"
    port: 32333
    nodePort: 32333
    targetPort:  emqx-dashboard
    protocol: TCP
  - name: "18083"
    port: 18083
    targetPort: 18083
  - name: "1883"
    port: 1883
    targetPort: 1883
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "8084"
    port: 8084
    targetPort: 8084
  - name: "11883"
    port: 11883
    targetPort: 11883
  selector:
    app: emqx
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: emqx
  labels:
        app: emqx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:latest
        ports:
        - name: emqx-dashboard
          containerPort: 18083
          containerPort: 1883
          containerPort: 11883
          containerPort: 8883
          containerPort: 8080
          containerPort: 8084
        env:
        - name: EMQX_CLUSTER__DISCOVERY
          value: k8s
        - name: EMQX_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__APISERVER
          value: http://10.10.75.12:8080
        - name: EMQX_CLUSTER__K8S__NAMESPACE
          value: default
        - name: EMQX_CLUSTER__K8S__SERVICE_NAME
          value: emqx
        - name: EMQX_CLUSTER__K8S__ADDRESS_TYPE
          value: ip
        - name: EMQX_CLUSTER__K8S__APP_NAME
          value: emqx
        tty: true
        volumeMounts:
                #- mountPath: /opt/emqx/etc/emqx.conf
                #name: emqx-hostpath0
           - mountPath: /etc/timezone
             name: emqx-hostpath1
             readOnly: true
           - mountPath: /etc/localtime
             name: emqx-hostpath2
             readOnly: true
      nodeSelector:
        vmname: loadtest3
      volumes:
        - hostPath:
            path: /home/ubuntu/git/IOT_load_test_client/infrastructure_components/publisher_subscriber/emqx/emqx.conf
            type: File
          name: emqx-hostpath0
        - hostPath:
            path: /etc/timezone
          name: emqx-hostpath1
        - hostPath:
            path: /etc/localtime
          name: emqx-hostpath2

