apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack-emq.yml --volumes hostPath
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: transformer
  name: transformer
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: transformer
    spec:
      containers:
      - env:
        - name: broker_hostname_key
          value: emq
        - name: broker_port_key
          value: "1883"
        - name: hash_table_name
          value: transformer_hash_table
        - name: log_level_key
          value: info
        - name: redis_log_keyname_key
          value: transformer_load_test_events
        - name: redis_server_hostname_key
          value: redis
        - name: redis_server_port_key
          value: "6379"
        - name: total_job_dequeued_count_redis_name_key
          value: total_consumed_count
        - name: total_job_enqueued_count_redis_name_key
          value: total_produced_count
        - name: transformer_key_name
          value: transformer
        - name: type_of_messaging_queue_key
          value: RabbitMQ
        image: transformer:latest
        imagePullPolicy: IfNotPresent
        name: transformer
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: transformer-hostpath0
        - mountPath: /etc/timezone
          name: transformer-hostpath1
          readOnly: true
        - mountPath: /etc/localtime
          name: transformer-hostpath2
          readOnly: true
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /media/psf/Home/git/IOT_load_test_client/kubernetes_yaml_files/core_components/emq/var/run/docker.sock
        name: transformer-hostpath0
      - hostPath:
          path: /media/psf/Home/git/IOT_load_test_client/kubernetes_yaml_files/core_components/emq/etc/timezone
        name: transformer-hostpath1
      - hostPath:
          path: /media/psf/Home/git/IOT_load_test_client/kubernetes_yaml_files/core_components/emq/etc/localtime
        name: transformer-hostpath2
status: {}
