apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
spec:
  selector:
    matchLabels:
      app: kafka
  maxUnavailable: 1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: common-infrastructure
spec:
  ports:
  - name: broker
    port: 9092
    nodePort: 32000
    protocol: TCP
    targetPort: kafka
  selector:
    app: kafka
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
  namespace: common-infrastructure
spec:
  serviceName: kafka
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: kafka
        imagePullPolicy: Always
        #image: gcr.io/google_containers/kubernetes-kafka:1.0-10.2.1
        image: wurstmeister/kafka:latest
        #resources:
        #  requests:
        #    memory: "1Gi"
        #    cpu: "0.5"
        securityContext:
         runAsUser: 0
        ports:
        - containerPort: 9092
          name: kafka
          protocol: TCP
        env:
        - name: KAFKA_HEAP_OPTS
          value : "-Xmx512M -Xms512M"
          #- name: KAFKA_OPTS
          #value: "-Dlogging.level=INFO"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper.common-infrastructure.svc.cluster.local:2181
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INSIDE:PLAINTEXT 
        - name: KAFKA_LISTENERS
          value: INSIDE://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INSIDE://:9092
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INSIDE
        - name: KAFKA_PORT
          value: "9092"
          #volumeMounts:
          #- name: datadir
          #mountPath: /var/lib/kafka
          #readinessProbe:
          #exec:
          # command:
          #  - sh
          #  - -c
          #  - "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server=localhost:9094"
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      nodeSelector:
        kubernetes.io/hostname: broker
        #volumeClaimTemplates:
        #- metadata:
        #name: datadir
        #spec:
        #accessModes: [ "ReadWriteOnce" ]
        # resources:
        # requests:
        #        storage: 10Gi
