apiVersion: v1
kind: Service
metadata:
  name: routing-manager
  creationTimestamp: null
  namespace: mec-poc
  labels:
     app: routing-manager
spec:
  ports:
  - name: "rest"
    port: 8080
    targetPort: 8080
  selector:
     app: routing-manager
status:
  loadBalancer: {}
