apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack-pulsar.yml --volumes hostPath
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
  namespace: loadtest
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: broker
    spec:
      containers:
      - args:
        - bin/pulsar
        - standalone
        image: apachepulsar/pulsar
        name: broker
        ports:
        - containerPort: 6650
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: broker-hostpath0
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: broker
      volumes:
      - hostPath:
          path: /media/psf/Home/git/IOT_load_test_client/kubernetes_yaml_files/core_components/pulsar/var/run/docker.sock
        name: broker-hostpath0
status: {}
