apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: routing-manager
  name: routing-manager
  namespace: mec-poc
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: routing-manager
    spec:
      containers:
      - env:
        - name: LOAD_TESTING
          value: true
        - name: KAFKA_ROUTE
          value: true
        - name: KAFKA_HOST_PORT
          value: 10.10.75.14:9092
        - name: KAFKA_IN_TOPIC
          value: PUBLISHER2
        - name: KAFKA_OUT_TOPIC
          value: SUBSCRIBER2
        image: ssriram1978/routing_manager:latest
        #imagePullPolicy: IfNotPresent
        name: routing-manager
        resources: {}
        volumeMounts:
            - mountPath: /var/run/docker.sock
              name: routing-manager-hostpath0
            - mountPath: /etc/timezone
              name: routing-manager-hostpath1
              readOnly: true
            - mountPath: /etc/localtime
              name: routing-manager-hostpath2
              readOnly: true
      restartPolicy: Always
      nodeSelector:
       kubernetes.io/hostname: transformer
      volumes:
                - hostPath:
                    path: /var/run/docker.sock
                  name: routing-manager-hostpath0
                - hostPath:
                    path: /etc/timezone
                  name: routing-manager-hostpath1
                - hostPath:
                    path: /etc/localtime
                  name: routing-manager-hostpath2
status: {}