apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack-rabbitmq.yml --volumes hostPath
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
  namespace: loadtest
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq
      namespace: loadtest
    spec:
      containers:
      - env:
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        image: rabbitmq:3.8-rc-management
        name: rabbitmq
        ports:
        - containerPort: 15672
        - containerPort: 5672
        - containerPort: 1883
        resources: {}
        volumeMounts:
        - mountPath: /etc/rabbitmq/enabled_plugins
          name: rabbitmq-hostpath0
        - mountPath: /etc/rabbitmq/rabbitmq-env.conf
          name: rabbitmq-hostpath1
        - mountPath: /etc/rabbitmq/rabbitmq-modified.conf
          name: rabbitmq-hostpath2
        - mountPath: /etc/rabbitmq/rabbitmq-definitions.json
          name: rabbitmq-hostpath3
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: broker
      volumes:
      - hostPath:
          path: /home/ubuntu/git/IOT_load_test_client/infrastructure_components/publisher_subscriber/rabbit_msgq_api/rabbitmq_conf_plugins/enabled_plugins
          type: File
        name: rabbitmq-hostpath0
      - hostPath:
          path: /home/ubuntu/git/IOT_load_test_client/infrastructure_components/publisher_subscriber/rabbit_msgq_api/rabbitmq_conf_plugins/rabbitmq-env.conf
          type: File
        name: rabbitmq-hostpath1
      - hostPath:
          path: /home/ubuntu/git/IOT_load_test_client/infrastructure_components/publisher_subscriber/rabbit_msgq_api/rabbitmq_conf_plugins/rabbitmq-modified.conf
          type: File
        name: rabbitmq-hostpath2
      - hostPath:
          path: /home/ubuntu/git/IOT_load_test_client/infrastructure_components/publisher_subscriber/rabbit_msgq_api/rabbitmq_conf_plugins/rabbitmq-definitions.json
          type: FileOrCreate
        name: rabbitmq-hostpath3
status: {}
