apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack-common.yml --volumes hostPath
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: transformer
  name: transformer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: transformer
    spec:
      containers:
      - env:
        - name: hash_table_name
          value: transformer_hash_table
        - name: log_level_key
          value: info
        - name: redis_log_keyname_key
          value: transformer_load_test_events
        - name: redis_server_hostname_key
          value: redis
        - name: redis_server_port_key
          value: "6379"
        - name: total_job_dequeued_count_redis_name_key
          value: total_consumed_count
        - name: total_job_enqueued_count_redis_name_key
          value: total_produced_count
        - name: transformer_key_name
          value: transformer
        - name: broker_hostname_key
          value: rabbitmq
        - name: broker_port_key
          value: "1883"
        - name: type_of_messaging_queue_key
          value: RabbitMQ
        image: transformer:latest
        name: transformer
        imagePullPolicy: IfNotPresent
        resources: {}
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: transformer-hostpath0
          - mountPath: /etc/timezone
            name: transformer-hostpath1
            readOnly: true
          - mountPath: /etc/localtime
            name: transformer-hostpath2
            readOnly: true
      restartPolicy: Always
      nodeSelector:
        vmname: loadtest4
      volumes:
            - hostPath:
                path: /var/run/docker.sock
              name: transformer-hostpath0
            - hostPath:
                path: /etc/timezone
              name: transformer-hostpath1
            - hostPath:
                path: /etc/localtime
              name: transformer-hostpath2
status: {}
