version: '3'
services:
  publisher:
    image: publisher:latest
    depends_on:
      - redis-commander
    ports:
      - "50000-50099:50000-50099"
      - "51000-51099:51000-51099"
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      publisher_key_name: "publisher"
      messages_per_second_key: "1000"
      test_duration_in_sec_key: "100"
      type_of_messaging_queue_key: 'ZeroMQ'
  subscriber:
    image: subscriber:latest
    depends_on:
      - transformer
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      publisher_hostname_key: "transformer"
      type_of_messaging_queue_key: 'ZeroMQ'
  transformer:
    image: transformer:latest
    depends_on:
      - publisher
    ports:
      - "52000-52099:52000-52099"
      - "53000-53099:53000-53099"
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      publisher_hostname_key: "publisher"
      type_of_messaging_queue_key: 'ZeroMQ'
  orchestrator:
    image: orchestrator:latest
    environment:
      distribute_ports: 'true'
      is_loopback_key: 'false'
