version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeuper
    ports:
     - "2181:2181"
    volumes:
     - "/etc/timezone:/etc/timezone:ro"
     - "/etc/localtime:/etc/localtime:ro"
  broker:
    image: wurstmeister/kafka:latest
    ports:
      - "9094:9094"
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - zookeeper
  publisher:
    image: publisher:latest
    depends_on:
      - broker
    deploy:
      replicas: 70
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      messages_per_second_key: "500"
      test_duration_in_sec_key: "10000"
      broker_hostname_key: "broker"
      broker_port_key: "9094"
      type_of_messaging_queue_key: 'WurstMeisterKafka'
  subscriber:
    image: subscriber:latest
    depends_on:
      - broker
    deploy:
      replicas: 70
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: "broker"
      broker_port_key: "9094"
      type_of_messaging_queue_key: 'WurstMeisterKafka'
  transformer:
    image: transformer:latest
    depends_on:
      - broker
    deploy:
      replicas: 70
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: "broker"
      broker_port_key: "9094"
      type_of_messaging_queue_key: 'WurstMeisterKafka'
  orchestrator:
    image: orchestrator:latest
    environment:
      distribute_ports: 'false'
      is_loopback_key: 'false'
