version: '3'
services:
  emq:
    image: emqx/emqx:latest
    ports:
        - "18083:18083"
        - "1883:1883"
        - "4369:4369"
    environment:
        EMQX_LOADED_PLUGINS: "emqx_auth_redis,emqx_recon,emqx_retainer,emqx_management,emqx_dashboard"
        EMQX_AUTH__REDIS__SERVER: "redis:6379"
  publisher:
    image: publisher:latest
    depends_on:
      - emq
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: 'emq'
      broker_port_key: "1883"
      messages_per_second_key: "1000"
      test_duration_in_sec_key: "100"
      type_of_messaging_queue_key: 'RabbitMQ'
  subscriber:
    image: subscriber:latest
    depends_on:
      - emq
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: "emq"
      broker_port_key: "1883"
      type_of_messaging_queue_key: 'RabbitMQ'
  transformer:
    image: transformer:latest
    depends_on:
      - emq
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: "emq"
      broker_port_key: "1883"
      type_of_messaging_queue_key: 'RabbitMQ'
  orchestrator:
    image: orchestrator:latest
    environment:
      distribute_ports: 'false'
      is_loopback_key: 'false'
