version: '3.7'
services:
  broker:
    image: apachepulsar/pulsar
    ports:
      - "6650:6650"
      - "8089:8080"
        # environment:
        #- PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        #- ./infrastructure_components/publisher_subscriber/pulsar_msgq_api/data:/pulsar/data
      # - "/etc/timezone:/etc/timezone:ro"
      # - "/etc/localtime:/etc/localtime:ro"
    command: ["bin/pulsar", "standalone"]
  publisher:
    image: publisher:latest
    depends_on:
      - broker
      - transformer
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: "broker"
      broker_port_key: "6650"
      messages_per_second_key: "1000"
      test_duration_in_sec_key: "100"
      type_of_messaging_queue_key: 'Pulsar'
  subscriber:
    image: subscriber:latest
    depends_on:
      - broker
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: "broker"
      broker_port_key: "6650"
      type_of_messaging_queue_key: 'Pulsar'
  transformer:
    image: transformer:latest
    depends_on:
      - broker
      - subscriber
    deploy:
      replicas: 1
      #      resources:
      #        limits:
      #          cpus: "0.8"
      #          memory: 2000M
      restart_policy:
        condition: none
    environment:
      broker_hostname_key: "broker"
      broker_port_key: "6650"
      type_of_messaging_queue_key: 'Pulsar'
  orchestrator:
    image: orchestrator:latest
    environment:
      distribute_ports: 'false'
      is_loopback_key: 'false'
