apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack-wurstmeister-kafka.yml --volumes
      hostPath
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: broker
    spec:
      containers:
      - env:
        - name: HOSTNAME_COMMAND
          value: 'docker info | grep ^Name: | cut -d'' '' -f 2'
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INSIDE://:9092,OUTSIDE://:9094
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INSIDE
        - name: KAFKA_LISTENERS
          value: INSIDE://:9092,OUTSIDE://:9094
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        image: wurstmeister/kafka:latest
        nodeSelector:
          vmname: loadtest3
        name: broker
        ports:
        - containerPort: 9094
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: broker-hostpath0
        - mountPath: /etc/timezone
          name: broker-hostpath1
          readOnly: true
        - mountPath: /etc/localtime
          name: broker-hostpath2
          readOnly: true
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /var/run/docker.sock
        name: broker-hostpath0
      - hostPath:
          path: /etc/timezone
        name: broker-hostpath1
      - hostPath:
          path: /etc/localtime
        name: broker-hostpath2
status: {}
