apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-stack-wurstmeister-kafka.yml --volumes
      hostPath
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
  namespace: common-infrastructure
spec:
  ports:
  - name: "9094"
    port: 9094
    targetPort: 9094
  selector:
    io.kompose.service: broker
status:
  loadBalancer: {}
