---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: common-infrastructure
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    filebeat.autodiscover:
        providers:
          - type: kubernetes
            hints.enabled: true
    output.logstash:
              hosts: ["logstash.elk.svc.cluster.local:5044"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-inputs
  namespace: common-infrastructure
  labels:
    k8s-app: filebeat
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true